### ISSUE TITLE
Código de Conducta sugerido

### ISSUE THREAD

**Issue by xombra** [cslve/codigo-de-conducta#1]
Sugerencia código de conducta: Basado en el de Ubuntu
- Ser considerado:
  Su trabajo será utilizado por otras personas, que a su vez dependerá del trabajo o proyectos de otros. cualquier decisión que usted realice afectarán a otros participantes y colegas.
- Ser respetuoso:
  La comunidad CSLve y todo aquel que participe debe tratar con respeto a todos y a cada uno de los participantes. Todos pueden hacer una valiosa colaboración. Tal vez, no siempre se estará de acuerdo, pero cuando exista un desacuerdo no es excusa para tratar de forma descortés a otro participante.
  Es importante recordar que toda comunidad hay personas que pueden diferir de su forma de trabajo, creencias o pensamientos, por lo que al evitar un mal trato o una mala respuesta hace sentir incómodos a otros participantes, haciendo que la tarea o proyecto que se esté ejecutando en ese momento no sea del todo productivo.
- Colaborar:
  La colaboración reduce la redundancia de un trabajo, siempre debemos mejorar la calidad de lo aportado, haciendolo de modo transparente, claro y sencillo. Si desea colaborar en una nueva tarea o discusión debe informar de sus ideas y del progreso que lleva. Brindando la posibilidad de que otras personas de la comunidad aporte en él.
  Los desacuerdos, bien sean políticos y/o técnicos, no es limitante en la realización de una tarea o proyecto, y debe solucionarse en forma civilizada. El objetivo importante no es evitar desacuerdos o diferentes puntos de vista (debido a que cada cabeza es un mundo), sino buscar como resolverlos de manera constructiva. 
  De no llegarse a un acuerdo y realmente quiere llevar la tarea o proyecto de una manera diferente, está en la completa libertad de crear un derivado, e invitar a la comunidad a que participe en él.

**Comment by NadiaGuerrera** [comment]
Me parece bien. Creo que en el respeto está implícito la asertividad y la tolerancia. Debería evitarse usar lenguaje no adecuado en el trato, con adjetivos descalificativos.
El respeto a las decisiones tomadas en concenso o por Mayoría.

Les voy a dar un consejo a aquellos que ya tienen historia en viejas rencillas. Vamos a enfocarnos en el punto a debatir y concretar propuestas...NO nos enganchemos con discusiones de vieja data sin resolver. Concretemos propuestas,acciones y soluciones.

**Comment by NadiaGuerrera** [comment]
Les voy a dar un consejo a aquellos que ya tienen historia en viejas rencillas. Vamos a enfocarnos en el punto a debatir y concretar propuestas...NO nos enganchemos con discusiones de vieja data sin resolver. Concretemos propuestas,acciones y soluciones.

**Comment by tarantindigital** [comment]
@xombra @NadiaGuerrera he agregado un pequeño insumo para la construcción colectiva del código de conducta, quedo a la espera de sus aportes y comentarios

**Comment by chudacontreras** [comment]
cerrado el issue por el tiempo que tiene
