### ISSUE TITLE
Cambios en parrafos

### ISSUE THREAD

**Issue by xombra** [cslve/codigo-de-conducta#10]
Sugiero que en la sección del primer párrafo:
... sin que la condiciones individuales de género, raza, credo, religión o afinidad política interfieran...

Sea cambiado por:
 sin que la condiciones individuales de género, raza, credo, religión, afinidad política, orientación sexual, o discapacidad interfieran...

Agregar la sección 1.- Normativa
- La publicación de información privada de otros, tales como direcciones físicas o electrónicas, sin el permiso explícito
- Otra conducta no ética o poco profesional
- Los miembros de la comunidad se comprometen a aplicar de manera justa y consistente de estos principios a todos los aspectos de esta comunidad.
- Este normativa de conducta se aplica tanto dentro de los espacios de la comunidad en medios electrónicos y/o digitales (Redes Sociales, Foros, Wiki, entre otros) y en los espacios públicos cuando un individuo está representando al proyecto o su comunidad.

**Comment by X3MBoy** [comment]
Me parece muy bien acertado el cambio de las condiciones individuales. Con respecto se debe definir que entendemos como conducta no ética o poco profesional, donde también cambiaría o por y/o. Del resto +1 por mi parte

**Comment by chudacontreras** [comment]
cerrado el issue por el tiempo que tiene
